/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32g0b0.h>
#include <stm32g070_gpio_driver.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

static void delayUS(uint32_t delay) {
	while(--delay);
}
int main(void)
{
	// Structure handle for the configuration
	GPIO_Handle_t GPIOUserConfig;

	//  Configuration for the GPIOA Pin 5
	GPIOUserConfig.pGPIOx = GPIOA;
	GPIOUserConfig.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;
	GPIOUserConfig.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUTPUT;
	GPIOUserConfig.GPIO_PinConfig.GPIO_PullUpPullDownConfig = GPIO_NO_PULLUP_PULLDOWN;
	GPIOUserConfig.GPIO_PinConfig.GPIO_OutputType = GPIO_OUTPUT_PUSH_PULL;
	GPIOUserConfig.GPIO_PinConfig.GPIO_OutputSpeed = GPIO_HIGH_SPEED;

	// Enable the Clock
	GPIO_PeripheralClockControl(GPIOA, ENABLE);

	// Initialize the GPIOA
	GPIO_Init(&GPIOUserConfig);


    /* Loop forever */
	for(;;) {
		// Toggle the Pin
		GPIOx_TogglePin(GPIOA, GPIO_PIN_NO_5);
		delayUS(250000);
	}
}
